[package]
name = "ngram_set"
version = "0.1.0"
authors = ["Paul Woolcock <paul@woolcock.us>"]

[dependencies.ngrams]
version = "0.1.1"

[dependencies.clippy]
version = "0.0.23"
optional = true

[features]
default = []
dev = ["clippy"]
